module.exports = {
    '@typescript-eslint/no-unused-vars': [
        'error',
        {
            vars: 'all',
            varsIgnorePattern: '^_|^props$',
            args: 'after-used',
            argsIgnorePattern: '^_',
            ignoreRestSiblings: true,
        },
    ],
    'vue/array-bracket-newline': ['error', 'consistent'],
    'vue/array-bracket-spacing': 'error',
    'vue/arrow-spacing': ['error', { before: true, after: true }],
    'vue/block-tag-newline': ['error', { singleline: 'always', multiline: 'always', maxEmptyLines: 0 }],
    'vue/brace-style': ['error', '1tbs'],
    'vue/comma-dangle': ['error', 'always-multiline'],
    'vue/comma-spacing': ['error', { before: false, after: true }],
    'vue/component-api-style': ['error', ['script-setup', 'composition']],
    'vue/component-name-in-template-casing': ['error', 'PascalCase', { registeredComponentsOnly: false }],
    'vue/component-tags-order': ['error', { order: ['script:not([setup])', 'script[setup]', 'template', 'style:not([scoped])', 'style[scoped]'] }],
    'vue/custom-event-name-casing': ['error', 'camelCase'],
    'vue/define-emits-delcaration': ['error', 'type-based'],
    'vue/define-macros-order': ['error', { order: ['defineProps', 'defineEmits'] }],
    'vue/define-props-declaration': ['error', 'type-based'],
    'vue/eqeqeq': ['error', 'always'],
    'vue/html-button-has-type': 'error',
    'vue/html-comment-content-spacing': ['error', 'always'],
    'vue/html-comment-indent': ['error', 4],
    'vue/html-comment-newline': ['error', { singleline: 'ignore', multiline: 'always' }],
    'vue/html-indent': ['error', 4],
    'vue/key-spacing': ['error', { beforeColon: false, afterColon: true }],
    'vue/keyword-spacing': ['error', { before: true, after: true }],
    'vue/max-attributes-per-line': ['error', { singleline: 5, multiline: 1 }],
    'vue/no-boolean-default': ['error', 'no-default'],
    'vue/no-duplicate-attr-inheritance': 'error',
    'vue/no-empty-component-block': 'error',
    'vue/no-irregular-whitespace': 'error',
    'vue/no-loss-of-precision': 'error',
    'vue/no-ref-object-destructure': 'error',
    'vue/no-required-prop-with-default': ['error', { autofix: false }],
    'vue/no-sparse-arrays': 'error',
    'vue/no-template-target-blank': 'error',
    'vue/no-this-in-before-route-enter': 'error',
    'vue/no-unused-vars': ['error', { ignorePattern: '^_' }],
    'vue/no-useless-mustaches': ['error', { ignoreStringEscape: true }],
    'vue/no-useless-v-bind': ['error', { ignoreStringEscape: true }],
    'vue/no-v-for-template-key': 'off',
    'vue/no-v-model-argument': 'off',
    'vue/no-v-text': 'error',
    'vue/object-curly-spacing': ['error', 'always'],
    'vue/padding-line-between-blocks': ['error', 'always'],
    'vue/prefer-prop-type-boolean-first': 'error',
    'vue/prefer-separate-static-class': 'error',
    'vue/prefer-template': ['error'],
    'vue/prefer-true-attribute-shorthand': 'error',
    'vue/quote-props': ['error', 'as-needed'],
    'vue/script-indent': ['error', 4, { baseIndent: 0, switchCase: 1 }],
    'vue/template-curly-spacing': ['error', 'never'],
    'vue/v-for-delimiter-style': ['error', 'in'],
}
