module.exports = {
    'brace-style': 'off',
    '@typescript-eslint/brace-style': ['warn', '1tbs'],
    'comma-dangle': 'off',
    '@typescript-eslint/comma-dangle': ['warn', 'always-multiline'],
    'comma-spacing': 'off',
    '@typescript-eslint/comma-spacing': ['warn', { before: false, after: true }],
    'func-call-spacing': 'off',
    '@typescript-eslint/func-call-spacing': ['warn', 'never'],
    'key-spacing': 'off',
    '@typescript-eslint/key-spacing': ['warn', { beforeColon: false, afterColon: true }],
    'keyword-spacing': 'off',
    '@typescript-eslint/keyword-spacing': ['warn', { before: true, after: true }],
    'no-unused-vars': 'off',
    '@typescript-eslint/no-unused-vars': [
        'error',
        {
            vars: 'all',
            varsIgnorePattern: '^_',
            args: 'after-used',
            argsIgnorePattern: '^_',
            ignoreRestSiblings: true,
        },
    ],
    'object-curly-spacing': 'off',
    '@typescript-eslint/object-curly-spacing': ['warn', 'always'],
    quotes: 'off',
    '@typescript-eslint/quotes': ['warn', 'single', { avoidEscape: true, allowTemplateLiterals: true }],
    semi: 'off',
    '@typescript-eslint/semi': ['warn', 'never'],
    'space-before-function-paren': 'off',
    '@typescript-eslint/space-before-function-paren': ['warn', { anonymous: 'never', named: 'never', asyncArrow: 'always' }],
    'space-infix-ops': 'off',
    '@typescript-eslint/space-infix-ops': 'warn',
}
